<a href="https://colab.research.google.com/github/Isaac-Nilberto/estudo-inadimplencia/blob/main/analise_inadiplencia_interativo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Etapa 1 - Análise dos dados

De acordo com os dados fornecidos, podemos mostrar o objetivo do trabalho: objetivo é tentar prever e minimizar a quantidade de BAD (cliente ruim = 1 e cliente bom = 0). O descritivo das variáveis:

clientId: Key para o tomador.

shopId: Key do empréstimo.

gender: Gênero do tomador.

maritalStatus: Estado civil do tomador.

age: Idade do tomador.

numberOfDependents: Quantidade de dependentes do tomador.

education: Nível educacional do tomador.

flagResidencialPhone: Flag se o tomador possui telefone residencial ou não.

areaCodeResidencialPhone: Codigo de area do telefone residencial.

bestPaymentDay: Melhor dia para pagamento do empréstimo.

shopRank: Ranking do empréstimo.

residenceType: Tipo de residência.

monthsInResidence: Tempo vivendo na mesma residência.

flagMothersName: Tomador registrou o nome da mãe na requisição de empréstimo.

flagFathersName: Tomador registrou o nome do pai na requisição de empréstimo.

flagResidenceTown_WorkingTown: Flag se o tomador vive na mesma cidade em que trabalha.

flagResidenceState_WorkingState: Flag se o tomador vive no mesmo estado que trabalha.

monthsInTheJob: Tempo no emprego atual.

professionCode: Código de profissão do tomador.

mateIncome: Renda do cônjuge do tomador.

flagResidencialAddress_PostalAddress: Flag de validação do CEP do tomador.

flagOtherCard: Y=Yes, N=No; Se o requerente possuir outro cartão de crédito ou private label

quantityBankingAccounts: Quantidade de contas bancárias do tomador.

flagMobilePhone: Flag se o tomador possui telefone celular.

flagContactPhone: Flag se o tomador possui um telefone de contato.

personalNetIncome: Renda média líquida mensal do tomador.

codeApplicationBooth: Código de onde a solicitação de empréstimo veio.

BAD: Flag se o tomador veio atrasou o pagamento do empréstimo.

Segue agora as classes das variáveis categóricas e binárias:

gender: F = Feminino e M = Masculino

maritalStatus: S = Solteiro, C = Casado, D = Divorciado, V = Viúvo e O = Outro.

residenceType: P = Própria, A = Aluguel, C = Mora com os pais e O = Outro.

flags: Y = Sim e N = Não

BAD: 0 = Cliente Adimplente e 1 = Cliente Inadimplente

In [206]:
# importing libraries
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
import seaborn as sns

# For the base of graph to be one graph interactive
pd.options.plotting.backend = 'plotly'

In [207]:
# importing dataset
data_base = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/base_de_dados_inadimplencia/Clients.csv')

In [208]:
# making a copy to save the data base

data_clients = data_base.copy()

In [209]:
# viewing info of data
data_clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 29 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Unnamed: 0                            40000 non-null  int64
 1   clientId                              40000 non-null  int64
 2   shopId                                40000 non-null  int64
 3   gender                                39997 non-null  object
 4   maritalStatus                         40000 non-null  object
 5   age                                   40000 non-null  int64
 6   numberOfDependents                    40000 non-null  int64
 7   education                             0 non-null      float64
 8   flagResidencialPhone                  40000 non-null  object
 9   areaCodeResidencialPhone              40000 non-null  int64
 10  bestPaymentDay                        40000 non-null  int64
 11  shopRank                              40000 non-null  int64
 12  residenceType                         40000 non-null  object
 13  monthsInResidence                     40000 non-null  int64
 14  flagMothersName                       40000 non-null  object
 15  flagFathersName                       40000 non-null  object
 16  flagResidenceTown_WorkingTown         40000 non-null  object
 17  flagResidenceState_WorkingState       40000 non-null  object
 18  monthsInTheJob                        40000 non-null  int64
 19  professionCode                        40000 non-null  int64
 20  mateIncome                            40000 non-null  float64
 21  flagResidencialAddress_PostalAddress  40000 non-null  object
 22  flagOtherCard                         40000 non-null  object
 23  quantityBankingAccounts               40000 non-null  int64
 24  flagMobilePhone                       40000 non-null  object
 25  flagContactPhone                      40000 non-null  object
 26  personalNetIncome                     40000 non-null  float64
 27  codeApplicationBooth                  40000 non-null  int64
 28  BAD                                   40000 non-null  int64
dtypes: float64(3), int64(14), object(12)
memory usage: 8.9+ MB

We can see in data I have in colomn education is null and gender has 3 lines null. I am going to cut education and to visualize of mode in gender to substitute of lines null.

In [210]:
# viewing of the head
data_clients.head()

,Unnamed: 0,clientId,shopId,gender,maritalStatus,age,numberOfDependents,education,flagResidencialPhone,areaCodeResidencialPhone,...,professionCode,mateIncome,flagResidencialAddress_PostalAddress,flagOtherCard,quantityBankingAccounts,flagMobilePhone,flagContactPhone,personalNetIncome,codeApplicationBooth,BAD
0,1,2,15,F,S,18,0,NaN,Y,31,...,853,0.0,Y,N,0,N,N,300.0,0,0
1,2,4,12,F,C,47,0,NaN,N,31,...,35,0.0,Y,N,0,N,N,304.0,0,0
2,3,5,16,F,S,28,0,NaN,Y,31,...,24,0.0,Y,N,0,N,N,250.0,0,0
3,4,6,24,M,S,26,0,NaN,N,31,...,999,0.0,Y,N,0,N,N,800.0,0,0
4,5,7,55,F,S,22,0,NaN,Y,31,...,999,0.0,Y,N,0,N,N,410.0,0,0

In [211]:
# viewing of sum data null
data_clients.isnull().sum()

Unnamed: 0                                  0
clientId                                    0
shopId                                      0
gender                                      3
maritalStatus                               0
age                                         0
numberOfDependents                          0
education                               40000
flagResidencialPhone                        0
areaCodeResidencialPhone                    0
bestPaymentDay                              0
shopRank                                    0
residenceType                               0
monthsInResidence                           0
flagMothersName                             0
flagFathersName                             0
flagResidenceTown_WorkingTown               0
flagResidenceState_WorkingState             0
monthsInTheJob                              0
professionCode                              0
mateIncome                                  0
flagResidencialAddress_PostalAddress        0
flagOtherCard                               0
quantityBankingAccounts                     0
flagMobilePhone                             0
flagContactPhone                            0
personalNetIncome                           0
codeApplicationBooth                        0
BAD                                         0
dtype: int64

In [212]:
# viewing of mode in data to gender
data_clients['gender'].mode()

0    F
dtype: object

In [213]:
# locating of columns
data_clients[data_clients['gender'].isnull()]

,Unnamed: 0,clientId,shopId,gender,maritalStatus,age,numberOfDependents,education,flagResidencialPhone,areaCodeResidencialPhone,...,professionCode,mateIncome,flagResidencialAddress_PostalAddress,flagOtherCard,quantityBankingAccounts,flagMobilePhone,flagContactPhone,personalNetIncome,codeApplicationBooth,BAD
4832,4833,6023,96,NaN,C,33,0,NaN,Y,31,...,508,0.0,Y,N,0,N,N,300.0,0,0
34642,34643,43254,22,NaN,O,37,0,NaN,Y,50,...,39,0.0,Y,N,0,N,N,626.0,0,1
35897,35898,44870,25,NaN,D,49,0,NaN,Y,31,...,131,0.0,Y,N,0,N,N,800.0,0,0

In [214]:
# replace of lines null to mode and cut of education

data_clients['gender'] = data_clients['gender'].apply(lambda x: 'F' if np.nan else x)

In [215]:
data_clients = data_clients.drop('education',axis = 1)
data_clients = data_clients.drop('Unnamed: 0', axis =1 )

In [216]:
data_clients.columns

Index(['clientId', 'shopId', 'gender', 'maritalStatus', 'age',
       'numberOfDependents', 'flagResidencialPhone',
       'areaCodeResidencialPhone', 'bestPaymentDay', 'shopRank',
       'residenceType', 'monthsInResidence', 'flagMothersName',
       'flagFathersName', 'flagResidenceTown_WorkingTown',
       'flagResidenceState_WorkingState', 'monthsInTheJob', 'professionCode',
       'mateIncome', 'flagResidencialAddress_PostalAddress', 'flagOtherCard',
       'quantityBankingAccounts', 'flagMobilePhone', 'flagContactPhone',
       'personalNetIncome', 'codeApplicationBooth', 'BAD'],
      dtype='object')

In [217]:
# viewing sum of lines null
data_clients.isnull().sum()

clientId                                0
shopId                                  0
gender                                  0
maritalStatus                           0
age                                     0
numberOfDependents                      0
flagResidencialPhone                    0
areaCodeResidencialPhone                0
bestPaymentDay                          0
shopRank                                0
residenceType                           0
monthsInResidence                       0
flagMothersName                         0
flagFathersName                         0
flagResidenceTown_WorkingTown           0
flagResidenceState_WorkingState         0
monthsInTheJob                          0
professionCode                          0
mateIncome                              0
flagResidencialAddress_PostalAddress    0
flagOtherCard                           0
quantityBankingAccounts                 0
flagMobilePhone                         0
flagContactPhone                        0
personalNetIncome                       0
codeApplicationBooth                    0
BAD                                     0
dtype: int64

In [218]:
# viewing of analysis descritive

data_clients.describe()

,clientId,shopId,age,numberOfDependents,areaCodeResidencialPhone,bestPaymentDay,shopRank,monthsInResidence,monthsInTheJob,professionCode,mateIncome,quantityBankingAccounts,personalNetIncome,codeApplicationBooth,BAD
count,40000.000000,40000.000000,40000.000000,40000.0,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.0,4.000000e+04,40000.0,40000.000000
mean,24982.227000,20.822950,34.649725,0.0,33.812275,15.313950,0.015950,152.921100,50.629500,484.611875,50.993333,0.0,9.752711e+03,0.0,0.197500
std,14428.531759,14.571913,13.076200,0.0,10.402941,7.159757,0.212124,136.096962,73.875139,382.102372,507.159125,0.0,4.856335e+05,0.0,0.398118
min,2.000000,1.000000,15.000000,0.0,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000e+00,0.0,0.000000
25%,12458.750000,12.000000,23.000000,0.0,31.000000,9.000000,0.000000,36.000000,12.000000,88.000000,0.000000,0.0,2.700000e+02,0.0,0.000000
50%,25058.500000,21.000000,33.000000,0.0,31.000000,12.000000,0.000000,120.000000,24.000000,514.000000,0.000000,0.0,4.000000e+02,0.0,0.000000
75%,37425.250000,24.000000,43.000000,0.0,31.000000,20.000000,0.000000,240.000000,60.000000,865.000000,0.000000,0.0,7.380000e+02,0.0,0.000000
max,50000.000000,96.000000,88.000000,0.0,70.000000,28.000000,3.000000,1188.000000,1176.000000,999.000000,70000.000000,0.0,3.852910e+07,0.0,1.000000

In [219]:
data_clients['gender'] = data_clients['gender'].apply(lambda x: 0 if 'F' else 1)

In [220]:
data_clients['gender'].dtype

dtype('int64')

In [221]:
data = data_clients.groupby(pd.Grouper(key='BAD',axis=0, sort= True)).sum()
data.plot(kind = 'bar')

In [222]:
#df.groupby(by=[pd.Grouper(level=29, freq='Y'), pd.Grouper(level=1)]).sum()
adiplentes = data_clients.groupby(['age','BAD'])['BAD'].count().unstack('BAD').fillna(0)
#adiplentes[[0, 1]].plot(kind='bar', stacked=True) 
adiplentes.plot(kind = 'bar')

In [226]:
adiplents = data_clients.groupby(['age', 'BAD', 'gender']).count()#['kind']
#adiplentes = data_clients.groupby('BAD').agg({'age': ['mean', 'min', 'max']})
adiplentes.plot(kind = 'bar')

TypeError: ignored